# Generated by Django 3.2.9 on 2021-12-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bokjiro',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('classification', models.CharField(blank=True, default='', max_length=15)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('contents', models.TextField(blank=True, default='')),
                ('interest', models.CharField(blank=True, default='', max_length=100)),
                ('family', models.CharField(blank=True, default='', max_length=100)),
                ('lifecycle', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('db_inserted_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bokjiro',
            },
        ),
        migrations.CreateModel(
            name='Mohw',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('contents', models.TextField(blank=True, default='')),
                ('createdDate', models.CharField(blank=True, default='', max_length=15)),
                ('db_inserted_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mohw',
            },
        ),
    ]
