# Generated by Django 3.2.9 on 2021-11-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Welfare',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.CharField(blank=True, default='', max_length=100)),
                ('interest', models.CharField(blank=True, default='', max_length=50)),
                ('family', models.CharField(blank=True, default='', max_length=50)),
                ('lifecycle', models.CharField(blank=True, default='', max_length=50)),
                ('age', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.classification')),
            ],
        ),
    ]
