# Generated by Django 3.2.9 on 2021-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryHealthWelfare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('contents', models.TextField(blank=True, default='')),
                ('createdDate', models.CharField(blank=True, default='', max_length=15)),
            ],
        ),
    ]
