# Generated by Django 3.2.9 on 2021-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_ministryhealthwelfare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministryhealthwelfare',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
